### ISSUE TITLE
Figure out how to get the input EEG data stream

### ISSUE THREAD

**Issue by matthewcso** [matthewcso/NRGYorkU-Brain-Computer-Music-Interface#1]

**Comment by Apeirogons** [comment]
Harley

**Comment by hglassman** [comment]
We will likely use Emotiv API software (e.g. BrainActivity Map), in which we may be able to stream continuous data to Python. This developer shows it may be possible.
https://www.youtube.com/watch?v=AhngudeSrFM

I can figure this out further once the headset is finished with repair. I've been in contact with the motherboard team.
