### ISSUE TITLE
Program real-time EEG data into classifier

### ISSUE THREAD

**Issue by hglassman** [matthewcso/NRGYorkU-Brain-Computer-Music-Interface#11]
Find a way to capture a robust resampling rate (e.g last 10 sec) for real-time EEG data to be continuously sent to the classifier. If possible, stream this through a preprocessing pipeline either on Python (preferably) or EEGLab intermediary to being sent to the classifier.

**Comment by matthewcso** [comment]
This task essentially falls under the domain of #1.
