### ISSUE TITLE
Attempt to train a classifier using the data from the nadzeri repository (Python or MATLAB)

### ISSUE THREAD

**Issue by matthewcso** [matthewcso/NRGYorkU-Brain-Computer-Music-Interface#4]
https://github.com/nadzeri/Realtime-EEG-Based-Emotion-Recognition

**Comment by Apeirogons** [comment]
Nicia (find a beginner-level task)

**Comment by hglassman** [comment]
If we wish to add a SVM, or Random-Forest, depending on how accurate the KNN is (87% is already pretty good) at classifying valence/arousal that could be another prospective step.

**Comment by matthewcso** [comment]
Not sure where the nadzeri data came from and, upon closer inspection, the dataset doesn't appear to be unprocessed EEG data. I recommend removing the data, there are many more datasets out there.
