### ISSUE TITLE
Determine how to control the valence and arousal in the Erlich code

### ISSUE THREAD

**Issue by matthewcso** [matthewcso/NRGYorkU-Brain-Computer-Music-Interface#5]

**Comment by Apeirogons** [comment]
Independently of the GUI

**Comment by Apeirogons** [comment]
I think I understand more about how this works: the Erlich code is controlled by two arrays: input.val and input.aro. However, to allow real-time music generation, we _might_ have to modify the MATLAB code itself, as it seems the function in the repo is set up to generate music from a static valence and arousal array.

**Comment by matthewcso** [comment]
Done.
