### ISSUE TITLE
Create a pipeline for extracting features from EEG (can use previous pipelines as reference)

### ISSUE THREAD

**Issue by matthewcso** [matthewcso/NRGYorkU-Brain-Computer-Music-Interface#8]

**Comment by hglassman** [comment]
Features may include spectral power, descriptive stats (Mean/Median/Variance/SD/Min_value/Max_value/Range/Skewness) x band activity.

We can select which features work based on whatever is more effective for the classifier, and the electrodes. https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_selection.html

**Comment by matthewcso** [comment]
going to make a new issue that is more targeted
